version: "3.8"

services:
  calculator-server:
    image: milicamasal/loan-calculator:latest
    container_name: calculator-server
    depends_on:
      - calculator-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://calculator-db:5432/calculator
      - SPRING_DATASOURCE_USERNAME=calculator
      - SPRING_DATASOURCE_PASSWORD=calculator
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
  calculator-db:
    image: postgres:13.1-alpine
    container_name: calculator-db
    volumes:
      - postgresvolume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=calculator
      - POSTGRES_PASSWORD=calculator

volumes:
  postgresvolume:
